/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 public/bulb.gltf -o components/Bulb.jsx
Author: lascoyt (https://sketchfab.com/lascoyt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/incandescent-light-bulb-36898e66c1d941efa24d7d6aea915a0b
Title: Incandescent Light Bulb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bulb.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.06}>
        <group scale={3.76}>
          <mesh geometry={nodes.Sphere001_0.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Sphere001_1.geometry} material={materials['Material.003']} />
        </group>
        <mesh geometry={nodes.Sphere_0.geometry} material={materials.Material} scale={3.76} />
        <mesh geometry={nodes.Cube_0.geometry} material={materials['Material.001']} position={[0.04, 0, -3.56]} scale={0.65} />
        <mesh geometry={nodes.BezierCurve_0.geometry} material={materials['Material.003']} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.BezierCurve001_0.geometry} material={materials['Material.003']} position={[0, 0.63, 0]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Cylinder_0.geometry} material={materials.wire_spiral} position={[-0.17, 0.57, -0.06]} rotation={[0, Math.PI / 2, 0]} scale={0.13} />
      </group>
    </group>
  )
}

useGLTF.preload('/bulb.gltf')
