/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 public/camera.gltf -o components/Camera.jsx
Author: TechnoCraft (https://sketchfab.com/TechnoCraft)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/yi-action-camera-7aa3640350c84c61a9e0600ae7b5fee3
Title: Yi Action Camera
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/camera.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -2]}>
        <mesh geometry={nodes.mainbody_mat_blcack_0.geometry} material={materials.mat_blcack} />
        <mesh geometry={nodes['mainbody_Material_#230_0'].geometry} material={materials.Material_230} />
      </group>
      <group position={[16.49, 0, 4]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['lens001_poly_Material_#37_0'].geometry} material={materials.Material_37} position={[-16.47, -1.51, 0]} />
      </group>
      <group position={[16.47, 0.22, -1.88]} scale={[1.55, 1.55, 1.22]}>
        <mesh geometry={nodes['Sphere001_Material_#231_0'].geometry} material={materials.Material_231} />
        <mesh geometry={nodes['Sphere001_Material_#37_0'].geometry} material={materials.Material_37} />
      </group>
      <mesh geometry={nodes['back_Material_#37_0'].geometry} material={materials.Material_37} position={[0, 0, -21]} />
      <mesh geometry={nodes['back_glass_Material_#2_0'].geometry} material={materials.Material_2} position={[0, 0, -21.51]} />
      <mesh geometry={nodes['c_Material_#37_0'].geometry} material={materials.Material_37} position={[16.5, 0, 0]} />
      <mesh geometry={nodes.Rectangle001__0.geometry} material={materials.Rectangle001__0} position={[-21.5, 0, 0]} />
      <mesh geometry={nodes['front_Material_#37_0'].geometry} material={materials.Material_37} />
      <mesh geometry={nodes['screen_Material_#39_0'].geometry} material={materials.Material_39} position={[3.11, 0, -21.5]} />
      <mesh geometry={nodes.Rectangle002_mat_blcack_0.geometry} material={materials.mat_blcack} position={[-13, 21.36, -12.99]} rotation={[-Math.PI / 2, -0.04, -1.57]} />
      <mesh geometry={nodes.Circle003__0.geometry} material={materials.Rectangle001__0} position={[-9, 21, -12.99]} rotation={[-Math.PI / 2, -0.03, -1.57]} />
      <mesh geometry={nodes.usb_cap_holder_mat_blcack_0.geometry} material={materials.mat_blcack} position={[30.82, -6.33, -4.07]} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/camera.gltf')
