/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 public/Computer.gltf -o components/Computer.jsx
Author: RigidStudios (https://sketchfab.com/RigidStudios)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pc-setup-mc-model-52cf9f4fcbee4aa38ab6691ab8087c0c
Title: PC Setup - MC Model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Computer.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.04, -0.04]} rotation={[-1.56, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material_6} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.none} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.material_5} />
      </group>
    </group>
  )
}

useGLTF.preload('/Computer.gltf')
