/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 public/computer.gltf -o components/Computer.jsx
Author: PIWTBAS.GaDev (https://sketchfab.com/bedzbern)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-computer-pc-setup-model-low-poly-pc-dd153ac3584b4e2e83a0bcd8d4d06247
Title: Free/ Computer / PC setup model ( low poly PC )
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/computer.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Cylinder_Material001_0.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder001_Material001_0.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube109_Material003_0.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Sphere__0.geometry} material={materials.Sphere__0} />
        <mesh geometry={nodes.Sphere001__0.geometry} material={materials.Sphere__0} />
        <mesh geometry={nodes.Sphere002__0.geometry} material={materials.Sphere__0} />
        <mesh geometry={nodes.Sphere003__0.geometry} material={materials.Sphere__0} />
        <mesh geometry={nodes.Cube113_Material015_0.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube114_Material016_0.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Cube116_Material016_0.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Cube117_Material016_0.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Plane_Material018_0.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Keyboard_Body_Material_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube001_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube002_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube003_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube004_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube005_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube006_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube007_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube008_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube009_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube010_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube011_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube012_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube013_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube014_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube015_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube016_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube017_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube018_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube019_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube020_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube021_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube022_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube024_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube026_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube027_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube028_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube023_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube025_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube029_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube030_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube031_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube032_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube033_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube035_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube036_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube037_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube038_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube039_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube040_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube041_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube042_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube046_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube047_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube048_Material010_0.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube049_Material010_0.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube050_Material010_0.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube051_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube053_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube052_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube054_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube055_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube060_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube061_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube062_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube063_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube064_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube065_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube056_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube057_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube058_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube059_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube066_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube067_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube068_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube069_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube070_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube071_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube072_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube073_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube074_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube075_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube076_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube077_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube078_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube079_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube080_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube081_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube082_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube083_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube084_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube085_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube086_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube087_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube088_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube089_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube090_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube091_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube092_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube093_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube094_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube034_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube043_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube044_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube045_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube095_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube096_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube097_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube098_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube099_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube100_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube101_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube102_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube104_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube103_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube105_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube106_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube107_Material008_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube108_Material007_0.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube110_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube111_Material006_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Cube112_Material005_0.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube_Material014_0.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Mouse_Material003_0.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Torus__0.geometry} material={materials.Sphere__0} position={[-1047.08, 39.86, 640.68]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.2, 0.17, 0.17]} />
      </group>
    </group>
  )
}

useGLTF.preload('/computer.gltf')
