/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 public/game.gltf -o components/Game.jsx
Author: Fred Drabble (https://sketchfab.com/FredDrabble)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ps5-controller-f75caead1dc1474195eb32a7f4c71117
Title: ps5 controller
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/game.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 13.49, -13.98]} rotation={[-0.56, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.06, 18.35, 5.65]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[29.94, -0.09, -3.71]}>
              <mesh geometry={nodes['Plane002_10_-_Default_0'].geometry} material={materials['10_-_Default']} />
              <mesh geometry={nodes['Plane002_11_-_Default_0'].geometry} material={materials['11_-_Default']} />
              <mesh geometry={nodes['Plane002_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
              <mesh geometry={nodes.Plane002_ultrablack_0.geometry} material={materials.ultrablack} />
              <mesh geometry={nodes.Plane002_standard_steel_0.geometry} material={materials.standard_steel} />
            </group>
          </group>
          <group position={[-0.06, 22.22, -26.99]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['touchpad_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[29.94, -31.78, -7.04]} />
          </group>
          <group position={[21.02, 27.17, 4.47]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.51, 1.51, 2.42]}>
            <group position={[0, 0, -2.62]}>
              <mesh geometry={nodes['Cylinder005_10_-_Default_0'].geometry} material={materials['10_-_Default']} />
              <mesh geometry={nodes.Cylinder005_ultrablack_0.geometry} material={materials.ultrablack} />
            </group>
          </group>
          <group position={[-20.82, 27.17, 4.47]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.51, 1.51, 2.42]}>
            <group position={[0, 0, -2.62]}>
              <mesh geometry={nodes['Cylinder006_10_-_Default_0'].geometry} material={materials['10_-_Default']} />
              <mesh geometry={nodes.Cylinder006_ultrablack_0.geometry} material={materials.ultrablack} />
            </group>
          </group>
          <group position={[41.14, 19.12, -38.6]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.topbuttons_ultrablack_0.geometry} material={materials.ultrablack} position={[-10.36, -45.18, -4.48]} />
          </group>
          <group position={[-41.22, 19.12, -38.6]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.topbuttons001_ultrablack_0.geometry} material={materials.ultrablack} position={[-10.36, -45.18, -4.48]} />
          </group>
          <mesh geometry={nodes.Box001_clear_0.geometry} material={materials.clear} position={[-43.2, 25.41, -23.14]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.73, 1.73, 0.5]} />
          <mesh geometry={nodes.Box002_clear_0.geometry} material={materials.clear} position={[-43.2, 25.41, -8]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[1.73, 1.73, 0.5]} />
          <mesh geometry={nodes.Box003_clear_0.geometry} material={materials.clear} position={[-50.76, 25.41, -15.57]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[1.73, 1.73, 0.5]} />
          <mesh geometry={nodes.Box004_clear_0.geometry} material={materials.clear} position={[-35.63, 25.41, -15.57]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.73, 1.73, 0.5]} />
          <mesh geometry={nodes.Cylinder001_clear_0.geometry} material={materials.clear} position={[42.71, 23.08, -25.44]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.93, 0.93, 1.01]} />
          <mesh geometry={nodes.Cylinder002_clear_0.geometry} material={materials.clear} position={[42.71, 23.08, -5.73]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.93, 0.93, 1.01]} />
          <mesh geometry={nodes.Cylinder003_clear_0.geometry} material={materials.clear} position={[33.28, 23.08, -15.73]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.93, 0.93, 1.01]} />
          <mesh geometry={nodes.Cylinder004_clear_0.geometry} material={materials.clear} position={[52.41, 23.08, -15.73]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.93, 0.93, 1.01]} />
          <mesh geometry={nodes.Cylinder007_rubber_0.geometry} material={materials.rubber} position={[21.07, 34.69, 4.49]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.12, 1.12, 0.23]} />
          <mesh geometry={nodes.Cylinder008_rubber_0.geometry} material={materials.rubber} position={[-20.86, 34.69, 4.49]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.12, 1.12, 0.23]} />
          <mesh geometry={nodes['Box005_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-32.27, 26.37, -31.56]} rotation={[-1.77, 0, 0]} scale={[1, 1, 0.56]} />
          <mesh geometry={nodes.bottombuttons_ultrablack_0.geometry} material={materials.ultrablack} position={[40.84, 6.45, -36.65]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.bottombuttons001_ultrablack_0.geometry} material={materials.ultrablack} position={[-41.09, 6.45, -36.65]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/game.gltf')
