/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 public/guitar.gltf -O components/Guitar.jsx
Author: DogeBites (https://sketchfab.com/DogeBites)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-acoustic-guitar-e70c949888e74e05af290420b8e39af5
Title: Low-Poly Acoustic Guitar
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/guitar.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Wood2} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Wood3} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Inside} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Grif} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Details} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Metal} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Metal} scale={[0.01, 1.75, 0.01]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.PlaneMaterial} rotation={[-Math.PI / 2, 0, 0]} scale={[-1, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/guitar.gltf')
