/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 public/innovation.gltf -o components/Innovation.jsx
Author: alkihuri (https://sketchfab.com/alkihuri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/levitation-scooter-f19e9182f3d146ed96061279fa19b9e5
Title: Levitation Scooter
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/innovation.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Engines_3" position={[0.73, 0, 0]} rotation={[0, 0, -0.94]} scale={[0.33, 0.22, 0.18]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Main} />
                <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials['Material.004']} />
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Material} />
                <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials['Material.005']} />
              </group>
              <group name="Ruler_4" position={[-0.76, 0.48, 0]} scale={0.08}>
                <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Ruler} />
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Main} />
                <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials['Material.002']} />
              </group>
              <group name="Cylinder_1" position={[-0.73, 0.51, 0]} rotation={[0, 0, -0.32]} scale={[0.11, 0.06, 0.11]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.003']} />
              </group>
              <group name="Body_2" position={[-0.22, 0.21, 0]} scale={[1.43, 0.35, 0.54]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Main} />
                <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.ForwardAPrt} />
                <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Material} />
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.005']} />
                <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['Material.003']} />
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.004']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/innovation.gltf')
