/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 public/Mic.gltf -o ./components/Mic.jsx
Author: Tomas Anglim (https://sketchfab.com/tomas.anglim.811)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mic-4ffc8ffb491f4db49308f4a730ae24a0
Title: Mic
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mic.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.7, 23.81, -0.93]} scale={0.96}>
        <mesh geometry={nodes.pCylinder1_lambert3_0.geometry} material={materials.lambert3} />
        <mesh geometry={nodes.pCylinder1_lambert2_0.geometry} material={materials.lambert2} />
      </group>
      <mesh geometry={nodes.pCylinder2_lambert2_0.geometry} material={materials.lambert2} position={[-0.67, 17.45, -1.62]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.63, 0.5, 0.63]} />
      <mesh geometry={nodes.pCylinder3_lambert2_0.geometry} material={materials.lambert2} position={[-3.47, 13.04, -0.87]} rotation={[0, 0, -0.54]} scale={[0.36, 5.14, 0.36]} />
      <mesh geometry={nodes.pCylinder4_lambert2_0.geometry} material={materials.lambert2} position={[-0.67, 17.45, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={[0.63, 0.5, 0.63]} />
    </group>
  )
}

useGLTF.preload('/Mic.gltf')
