import Head from "next/head";
import { BsPlusLg } from "react-icons/bs";
import Events from "../components/Events";
import CountDown from "../components/CountDown";
import { useEffect, useState } from "react";
import Cultutal from "../components/Cultural";
import Team from "../components/Team";
import SearchEvent from "../components/SearchEvent";

export default function Home() {
  const companyCommonStyles =
    "min-h-[70px] sm:px-0 px-2 sm:min-w-[120px] flex justify-center items-center border-[0.5px] border-gray-400 text-sm font-light text-white";
  return (
    <>
      <Head>
        <title>ResonanceXII</title>
        <meta name="description" content="Generated by ResonanceXII" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="bg-gradient-1 w-screen h-full py-28 flex items-center justify-start flex-col">
        <div className="flex justify-center items-center m-4 flex-col text-center">
          <CountDown />
          <div>
            <h1 className="text-gradient font-bold text-3xl md:text-6xl tracking-wide">
              Dive Into the Euphoria <br /> of all things Tech!
            </h1>
            <p className="text-base md:text-lg mt-2">
              at the heart of CEMK, Kolaghat
            </p>
          </div>
        </div>
        <div className="w-full flex justify-center items-center mt-4 mb-20">
          <SearchEvent />
        </div>
      </section>
      <section className="bg-gradient-2 w-screen relative min-h-screen">
        <div className="static md:absolute md:-top-24 md:left-0 md:right-0 flex justify-center items-center flex-wrap p-4 z-0">
          <div className="white-glassmorphism rounded-lg py-6 px-16 text-center m-4 max-w-max z-0">
            <span className="inline-flex items-center justify-center text-6xl">
              30 <BsPlusLg className="w-6 h-6 ml-2" />
            </span>
            <p className="uppercase mt-4">Events</p>
          </div>
          <div className="white-glassmorphism rounded-lg py-6 px-16 text-center m-4 max-w-max">
            <span className="inline-flex items-center justify-center text-6xl">
              30 <BsPlusLg className="w-6 h-6 ml-2" />
            </span>
            <p className="uppercase mt-4">Events</p>
          </div>
          <div className="white-glassmorphism rounded-lg py-6 px-16 text-center m-4 max-w-max">
            <span className="inline-flex items-center justify-center text-6xl">
              30 <BsPlusLg className="w-6 h-6 ml-2" />
            </span>
            <p className="uppercase mt-4">Events</p>
          </div>
          <div className="white-glassmorphism rounded-lg py-6 px-16 text-center m-4 max-w-max">
            <span className="inline-flex items-center justify-center text-6xl">
              30 <BsPlusLg className="w-6 h-6 ml-2" />
            </span>
            <p className="uppercase mt-4">Events</p>
          </div>
        </div>
        <div className="pt-20">
          <Events />
        </div>
      </section>
      <Cultutal />
      <Team />
    </>
  );
}
